#!/bin/bash

#PBS -l nodes=1:ppn=1,walltime=6:00:00
#PBS -N FindCpG
#PBS -M klc328@nyu.edu
#PBS -m abe
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}

# ------------------------------------------------------------------------------
# Run pipeline
# ------------------------------------------------------------------------------

working_dir=$PBS_O_WORKDIR

cd $working_dir

perl scripts/find_CpGs.pl > results/papAnu2.CpG.bed

exit;
