#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=40:00:00
#PBS -N GatkGenotype
#PBS -M klc328@nyu.edu
#PBS -m abe
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}.${PBS_ARRAYID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}.${PBS_ARRAYID}

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

working_dir=$PBS_O_WORKDIR

module load jdk/1.8.0

GATK=/home/klc328/downloads/gatk-3.5
GENOME_FA=genomes/papAnu2/papAnu2.fa
GENOME_NAME=baboon

module load vcftools/intel/0.1.13
module load tabix/intel/0.2.6

# ------------------------------------------------------------------------------
# Run program
# ------------------------------------------------------------------------------

cd $working_dir

if [ "$PBS_ARRAYID" -eq 21 ]; then
    CHROM=X
else
    CHROM=$PBS_ARRAYID
fi

BAMS=(`ls results/*.PE.bwa.${GENOME_NAME}.passed.realn.bam`)

# Make output directory
mkdir ${GENOME_NAME}_snps

count=0
for b in ${BAMS[*]}; do

    count=`expr $count + 1`

    java -jar ${GATK}/GenomeAnalysisTK.jar \
        -T UnifiedGenotyper \
        -R ${GENOME_FA} \
        -I ${b} \
        -stand_call_conf 50.0 \
        -stand_emit_conf 10.0 \
        -o ${GENOME_NAME}_snps/chr${CHROM}.raw.snps.indels.tmp${count}.vcf \
        -nct 4 \
        -nt 8 \
        -L chr${CHROM}
    
    bgzip ${GENOME_NAME}_snps/chr${CHROM}.raw.snps.indels.tmp${count}.vcf
    tabix -p vcf ${GENOME_NAME}_snps/chr${CHROM}.raw.snps.indels.tmp${count}.vcf.gz

done

# Merge this chromosome's VCFs
TMP_VCFS=(`ls ${GENOME_NAME}_snps/chr${CHROM}.raw.snps.indels.tmp*.vcf.gz`)
vcf-merge ${TMP_VCFS[*]} > ${GENOME_NAME}_snps/chr${CHROM}.INDIV.raw.snps.indels.vcf

exit;
