#!/bin/bash

#PBS -l nodes=1:ppn=1,walltime=6:00:00,mem=5gb
#PBS -N GetGC
#PBS -M klc328@nyu.edu
#PBS -m abe
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}

# ------------------------------------------------------------------------------
# Run pipeline
# ------------------------------------------------------------------------------

working_dir=$PBS_O_WORKDIR

cd $working_dir

sh scripts/get_RADtag_GC.sh

exit;
