#!/bin/bash

#PBS -l nodes=1:ppn=1,walltime=6:00:00
#PBS -N RadCov
#PBS -M klc328@nyu.edu
#PBS -m abe
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}.${PBS_ARRAYID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}.${PBS_ARRAYID}

# ------------------------------------------------------------------------------
# Run pipeline
# ------------------------------------------------------------------------------

working_dir=$PBS_O_WORKDIR

cd $working_dir

module load bedtools/intel/2.25.0

ALL_BAMS=($(ls NGS-map/results/fecalRAD-BC*-BC*.PE.bwa.baboon.passed.realn.bam | \
    grep -v samp))
THIS_BAM=${ALL_BAMS[$PBS_ARRAYID]}

echo "Computing RADtag coverage for individual with BAM file ${THIS_BAM}..."

sh scripts/get_RADtag_cov.sh $THIS_BAM

exit;
