#!/bin/bash

cd demultiplex/demultiplexed/

# Move demultiplexed samples to new folder (ignoring unknown matches and matches to unused barcodes)

mv FecalSeq1_BC1-BC1_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq1_BC1-BC1_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq1_BC1-BC2_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq1_BC1-BC2_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq1_BC1-BC3_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq1_BC1-BC3_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq1_BC2-BC4_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq1_BC2-BC4_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq1_BC2-BC5_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq1_BC2-BC5_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq1_BC2-BC6_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq1_BC2-BC6_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq1_BC3-BC7_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq1_BC3-BC7_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq1_BC3-BC8_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq1_BC3-BC8_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq1_BC4-BC1_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq1_BC4-BC1_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq1_BC4-BC2_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq1_BC4-BC2_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC1_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC1_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC2_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC2_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC3_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC3_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC4_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC4_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC5_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC5_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC6_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC6_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC7_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC7_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC8_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC8_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC9_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC9_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC10_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC10_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC11_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC11_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq2_BC1-BC12_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq2_BC1-BC12_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC1_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC1_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC2_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC2_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC3_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC3_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC4_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC4_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC5_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC5_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC6_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC6_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC7_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC7_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC8_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC8_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC9_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC9_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC10_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC10_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC11_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC11_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3a_BC1-BC12_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3a_BC1-BC12_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC1_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC1_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC2_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC2_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC3_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC3_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC4_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC4_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC5_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC5_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC6_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC6_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC7_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC7_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC8_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC8_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC9_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC9_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC10_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC10_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC11_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC11_R2.fastq ${SCRATCH}/demultiplexed/;
mv FecalSeq3b_BC1-BC12_R1.fastq ${SCRATCH}/demultiplexed/; mv FecalSeq3b_BC1-BC12_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue1_BC1-BC10_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue1_BC1-BC10_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue1_BC1-BC11_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue1_BC1-BC11_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue1_BC1-BC12_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue1_BC1-BC12_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue1_BC2-BC11_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue1_BC2-BC11_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue1_BC2-BC12_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue1_BC2-BC12_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC1_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC1_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC2_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC2_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC3_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC3_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC4_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC4_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC5_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC5_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC6_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC6_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC7_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC7_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC8_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC8_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC9_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC9_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC10_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC10_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC11_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC11_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC1-BC12_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC1-BC12_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC1_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC1_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC2_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC2_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC3_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC3_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC4_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC4_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC5_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC5_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC6_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC6_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC7_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC7_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC8_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC8_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC9_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC9_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC10_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC10_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC11_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC11_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC2-BC12_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC2-BC12_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC3-BC1_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC3-BC1_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC3-BC2_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC3-BC2_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC3-BC3_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC3-BC3_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC3-BC4_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC3-BC4_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC3-BC5_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC3-BC5_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC3-BC6_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC3-BC6_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC3-BC7_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC3-BC7_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC3-BC8_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC3-BC8_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC4-BC1_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC4-BC1_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC4-BC2_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC4-BC2_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC4-BC3_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC4-BC3_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC4-BC4_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC4-BC4_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC4-BC5_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC4-BC5_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC4-BC6_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC4-BC6_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC4-BC7_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC4-BC7_R2.fastq ${SCRATCH}/demultiplexed/;
mv Kafue2a_BC4-BC8_R1.fastq ${SCRATCH}/demultiplexed/; mv Kafue2a_BC4-BC8_R2.fastq ${SCRATCH}/demultiplexed/;

cd ${SCRATCH}/demultiplexed/

# Concatenate identical runs

cat FecalSeq3a_BC1-BC1_R1.fastq FecalSeq3b_BC1-BC1_R1.fastq > FecalSeq3_BC1-BC1_R1.fastq; cat FecalSeq3a_BC1-BC1_R2.fastq FecalSeq3b_BC1-BC1_R2.fastq > FecalSeq3_BC1-BC1_R2.fastq;
cat FecalSeq3a_BC1-BC2_R1.fastq FecalSeq3b_BC1-BC2_R1.fastq > FecalSeq3_BC1-BC2_R1.fastq; cat FecalSeq3a_BC1-BC2_R2.fastq FecalSeq3b_BC1-BC2_R2.fastq > FecalSeq3_BC1-BC2_R2.fastq;
cat FecalSeq3a_BC1-BC3_R1.fastq FecalSeq3b_BC1-BC3_R1.fastq > FecalSeq3_BC1-BC3_R1.fastq; cat FecalSeq3a_BC1-BC3_R2.fastq FecalSeq3b_BC1-BC3_R2.fastq > FecalSeq3_BC1-BC3_R2.fastq;
cat FecalSeq3a_BC1-BC4_R1.fastq FecalSeq3b_BC1-BC4_R1.fastq > FecalSeq3_BC1-BC4_R1.fastq; cat FecalSeq3a_BC1-BC4_R2.fastq FecalSeq3b_BC1-BC4_R2.fastq > FecalSeq3_BC1-BC4_R2.fastq;
cat FecalSeq3a_BC1-BC5_R1.fastq FecalSeq3b_BC1-BC5_R1.fastq > FecalSeq3_BC1-BC5_R1.fastq; cat FecalSeq3a_BC1-BC5_R2.fastq FecalSeq3b_BC1-BC5_R2.fastq > FecalSeq3_BC1-BC5_R2.fastq;
cat FecalSeq3a_BC1-BC6_R1.fastq FecalSeq3b_BC1-BC6_R1.fastq > FecalSeq3_BC1-BC6_R1.fastq; cat FecalSeq3a_BC1-BC6_R2.fastq FecalSeq3b_BC1-BC6_R2.fastq > FecalSeq3_BC1-BC6_R2.fastq;
cat FecalSeq3a_BC1-BC7_R1.fastq FecalSeq3b_BC1-BC7_R1.fastq > FecalSeq3_BC1-BC7_R1.fastq; cat FecalSeq3a_BC1-BC7_R2.fastq FecalSeq3b_BC1-BC7_R2.fastq > FecalSeq3_BC1-BC7_R2.fastq;
cat FecalSeq3a_BC1-BC8_R1.fastq FecalSeq3b_BC1-BC8_R1.fastq > FecalSeq3_BC1-BC8_R1.fastq; cat FecalSeq3a_BC1-BC8_R2.fastq FecalSeq3b_BC1-BC8_R2.fastq > FecalSeq3_BC1-BC8_R2.fastq;
cat FecalSeq3a_BC1-BC9_R1.fastq FecalSeq3b_BC1-BC9_R1.fastq > FecalSeq3_BC1-BC9_R1.fastq; cat FecalSeq3a_BC1-BC9_R2.fastq FecalSeq3b_BC1-BC9_R2.fastq > FecalSeq3_BC1-BC9_R2.fastq;
cat FecalSeq3a_BC1-BC10_R1.fastq FecalSeq3b_BC1-BC10_R1.fastq > FecalSeq3_BC1-BC10_R1.fastq; cat FecalSeq3a_BC1-BC10_R2.fastq FecalSeq3b_BC1-BC10_R2.fastq > FecalSeq3_BC1-BC10_R2.fastq;
cat FecalSeq3a_BC1-BC11_R1.fastq FecalSeq3b_BC1-BC11_R1.fastq > FecalSeq3_BC1-BC11_R1.fastq; cat FecalSeq3a_BC1-BC11_R2.fastq FecalSeq3b_BC1-BC11_R2.fastq > FecalSeq3_BC1-BC11_R2.fastq;
cat FecalSeq3a_BC1-BC12_R1.fastq FecalSeq3b_BC1-BC12_R1.fastq > FecalSeq3_BC1-BC12_R1.fastq; cat FecalSeq3a_BC1-BC12_R2.fastq FecalSeq3b_BC1-BC12_R2.fastq > FecalSeq3_BC1-BC12_R2.fastq;

# Copy samples to NGS-map data folder

cp FecalSeq1_BC1-BC1_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF02a.read1.fastq; cp FecalSeq1_BC1-BC1_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF02a.read2.fastq;
cp FecalSeq1_BC1-BC2_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF05a.read1.fastq; cp FecalSeq1_BC1-BC2_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF05a.read2.fastq;
cp FecalSeq1_BC1-BC3_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF07a.read1.fastq; cp FecalSeq1_BC1-BC3_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF07a.read2.fastq;
cp FecalSeq1_BC2-BC4_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF09a.read1.fastq; cp FecalSeq1_BC2-BC4_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF09a.read2.fastq;
cp FecalSeq1_BC2-BC5_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_051a.read1.fastq; cp FecalSeq1_BC2-BC5_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_051a.read2.fastq;
cp FecalSeq1_BC2-BC6_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_053.read1.fastq; cp FecalSeq1_BC2-BC6_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_053.read2.fastq;
cp FecalSeq1_BC3-BC7_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB02a.read1.fastq; cp FecalSeq1_BC3-BC7_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB02a.read2.fastq;
cp FecalSeq1_BC3-BC8_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB05a.read1.fastq; cp FecalSeq1_BC3-BC8_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB05a.read2.fastq;
cp FecalSeq1_BC4-BC1_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB07.read1.fastq; cp FecalSeq1_BC4-BC1_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB07.read2.fastq;
cp FecalSeq1_BC4-BC2_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB09a.read1.fastq; cp FecalSeq1_BC4-BC2_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB09a.read2.fastq;
cp FecalSeq2_BC1-BC1_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF01a.read1.fastq; cp FecalSeq2_BC1-BC1_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF01a.read2.fastq;
cp FecalSeq2_BC1-BC2_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF02b.read1.fastq; cp FecalSeq2_BC1-BC2_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF02b.read2.fastq;
cp FecalSeq2_BC1-BC3_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF07b.read1.fastq; cp FecalSeq2_BC1-BC3_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF07b.read2.fastq;
cp FecalSeq2_BC1-BC4_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF10a.read1.fastq; cp FecalSeq2_BC1-BC4_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF10a.read2.fastq;
cp FecalSeq2_BC1-BC5_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_030a.read1.fastq; cp FecalSeq2_BC1-BC5_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_030a.read2.fastq;
cp FecalSeq2_BC1-BC6_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_050a.read1.fastq; cp FecalSeq2_BC1-BC6_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_050a.read2.fastq;
cp FecalSeq2_BC1-BC7_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_065a.read1.fastq; cp FecalSeq2_BC1-BC7_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_065a.read2.fastq;
cp FecalSeq2_BC1-BC8_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_069a.read1.fastq; cp FecalSeq2_BC1-BC8_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_069a.read2.fastq;
cp FecalSeq2_BC1-BC9_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_066.read1.fastq; cp FecalSeq2_BC1-BC9_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_066.read2.fastq;
cp FecalSeq2_BC1-BC10_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_148.read1.fastq; cp FecalSeq2_BC1-BC10_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_148.read2.fastq;
cp FecalSeq2_BC1-BC11_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB01a.read1.fastq; cp FecalSeq2_BC1-BC11_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB01a.read2.fastq;
cp FecalSeq2_BC1-BC12_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB10a.read1.fastq; cp FecalSeq2_BC1-BC12_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB10a.read2.fastq;
cp FecalSeq3_BC1-BC1_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF01b.read1.fastq; cp FecalSeq3_BC1-BC1_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF01b.read2.fastq;
cp FecalSeq3_BC1-BC2_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF02c.read1.fastq; cp FecalSeq3_BC1-BC2_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF02c.read2.fastq;
cp FecalSeq3_BC1-BC3_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF05b.read1.fastq; cp FecalSeq3_BC1-BC3_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF05b.read2.fastq;
cp FecalSeq3_BC1-BC4_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF02d.read1.fastq; cp FecalSeq3_BC1-BC4_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF02d.read2.fastq;
cp FecalSeq3_BC1-BC5_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF09b.read1.fastq; cp FecalSeq3_BC1-BC5_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF09b.read2.fastq;
cp FecalSeq3_BC1-BC6_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF10b.read1.fastq; cp FecalSeq3_BC1-BC6_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF10b.read2.fastq;
cp FecalSeq3_BC1-BC7_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_050b.read1.fastq; cp FecalSeq3_BC1-BC7_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_050b.read2.fastq;
cp FecalSeq3_BC1-BC8_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_050c.read1.fastq; cp FecalSeq3_BC1-BC8_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_050c.read2.fastq;
cp FecalSeq3_BC1-BC9_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_051b.read1.fastq; cp FecalSeq3_BC1-BC9_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_051b.read2.fastq;
cp FecalSeq3_BC1-BC10_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF05c.read1.fastq; cp FecalSeq3_BC1-BC10_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TF05c.read2.fastq;
cp FecalSeq3_BC1-BC11_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_069b.read1.fastq; cp FecalSeq3_BC1-BC11_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_069b.read2.fastq;
cp FecalSeq3_BC1-BC12_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_051c.read1.fastq; cp FecalSeq3_BC1-BC12_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_051c.read2.fastq;
cp Kafue1_BC1-BC10_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB01b.read1.fastq; cp Kafue1_BC1-BC10_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB01b.read2.fastq;
cp Kafue1_BC1-BC11_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB02b.read1.fastq; cp Kafue1_BC1-BC11_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB02b.read2.fastq;
cp Kafue1_BC1-BC12_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB09b.read1.fastq; cp Kafue1_BC1-BC12_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB09b.read2.fastq;
cp Kafue1_BC2-BC11_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB05b.read1.fastq; cp Kafue1_BC2-BC11_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB05b.read2.fastq;
cp Kafue1_BC2-BC12_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB10b.read1.fastq; cp Kafue1_BC2-BC12_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/TB10b.read2.fastq;
cp Kafue2a_BC1-BC1_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_220.read1.fastq; cp Kafue2a_BC1-BC1_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_220.read2.fastq;
cp Kafue2a_BC1-BC2_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_001.read1.fastq; cp Kafue2a_BC1-BC2_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_001.read2.fastq;
cp Kafue2a_BC1-BC3_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_007.read1.fastq; cp Kafue2a_BC1-BC3_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_007.read2.fastq;
cp Kafue2a_BC1-BC4_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_029.read1.fastq; cp Kafue2a_BC1-BC4_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_029.read2.fastq;
cp Kafue2a_BC1-BC5_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_032.read1.fastq; cp Kafue2a_BC1-BC5_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_032.read2.fastq;
cp Kafue2a_BC1-BC6_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_034.read1.fastq; cp Kafue2a_BC1-BC6_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_034.read2.fastq;
cp Kafue2a_BC1-BC7_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_039.read1.fastq; cp Kafue2a_BC1-BC7_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_039.read2.fastq;
cp Kafue2a_BC1-BC8_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_057.read1.fastq; cp Kafue2a_BC1-BC8_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_057.read2.fastq;
cp Kafue2a_BC1-BC9_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_003.read1.fastq; cp Kafue2a_BC1-BC9_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_003.read2.fastq;
cp Kafue2a_BC1-BC10_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_044.read1.fastq; cp Kafue2a_BC1-BC10_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_044.read2.fastq;
cp Kafue2a_BC1-BC11_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_041.read1.fastq; cp Kafue2a_BC1-BC11_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_041.read2.fastq;
cp Kafue2a_BC1-BC12_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_042.read1.fastq; cp Kafue2a_BC1-BC12_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_042.read2.fastq;
cp Kafue2a_BC2-BC1_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_221.read1.fastq; cp Kafue2a_BC2-BC1_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_221.read2.fastq;
cp Kafue2a_BC2-BC2_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_227.read1.fastq; cp Kafue2a_BC2-BC2_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_227.read2.fastq;
cp Kafue2a_BC2-BC3_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_004.read1.fastq; cp Kafue2a_BC2-BC3_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_004.read2.fastq;
cp Kafue2a_BC2-BC4_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_005.read1.fastq; cp Kafue2a_BC2-BC4_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_005.read2.fastq;
cp Kafue2a_BC2-BC5_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_030.read1.fastq; cp Kafue2a_BC2-BC5_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_030.read2.fastq;
cp Kafue2a_BC2-BC6_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_035.read1.fastq; cp Kafue2a_BC2-BC6_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_035.read2.fastq;
cp Kafue2a_BC2-BC7_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_041.read1.fastq; cp Kafue2a_BC2-BC7_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_041.read2.fastq;
cp Kafue2a_BC2-BC8_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_001.read1.fastq; cp Kafue2a_BC2-BC8_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_001.read2.fastq;
cp Kafue2a_BC2-BC9_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_004.read1.fastq; cp Kafue2a_BC2-BC9_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_004.read2.fastq;
cp Kafue2a_BC2-BC10_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_065b.read1.fastq; cp Kafue2a_BC2-BC10_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_065b.read2.fastq;
cp Kafue2a_BC2-BC11_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_030b.read1.fastq; cp Kafue2a_BC2-BC11_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_030b.read2.fastq;
cp Kafue2a_BC2-BC12_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_039.read1.fastq; cp Kafue2a_BC2-BC12_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_039.read2.fastq;
cp Kafue2a_BC3-BC1_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_218.read1.fastq; cp Kafue2a_BC3-BC1_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_218.read2.fastq;
cp Kafue2a_BC3-BC2_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_224.read1.fastq; cp Kafue2a_BC3-BC2_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_224.read2.fastq;
cp Kafue2a_BC3-BC3_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_225.read1.fastq; cp Kafue2a_BC3-BC3_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ06_225.read2.fastq;
cp Kafue2a_BC3-BC4_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_042.read1.fastq; cp Kafue2a_BC3-BC4_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_042.read2.fastq;
cp Kafue2a_BC3-BC5_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_045.read1.fastq; cp Kafue2a_BC3-BC5_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_045.read2.fastq;
cp Kafue2a_BC3-BC6_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_047.read1.fastq; cp Kafue2a_BC3-BC6_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_047.read2.fastq;
cp Kafue2a_BC3-BC7_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_100.read1.fastq; cp Kafue2a_BC3-BC7_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/BZ07_100.read2.fastq;
cp Kafue2a_BC3-BC8_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_036.read1.fastq; cp Kafue2a_BC3-BC8_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_036.read2.fastq;
cp Kafue2a_BC4-BC1_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_054.read1.fastq; cp Kafue2a_BC4-BC1_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_054.read2.fastq;
cp Kafue2a_BC4-BC2_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_056.read1.fastq; cp Kafue2a_BC4-BC2_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_056.read2.fastq;
cp Kafue2a_BC4-BC3_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_058.read1.fastq; cp Kafue2a_BC4-BC3_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_058.read2.fastq;
cp Kafue2a_BC4-BC4_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_059.read1.fastq; cp Kafue2a_BC4-BC4_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_059.read2.fastq;
cp Kafue2a_BC4-BC5_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_15_003.read1.fastq; cp Kafue2a_BC4-BC5_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_15_003.read2.fastq;
cp Kafue2a_BC4-BC6_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_15_004.read1.fastq; cp Kafue2a_BC4-BC6_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_15_004.read2.fastq;
cp Kafue2a_BC4-BC7_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_15_005.read1.fastq; cp Kafue2a_BC4-BC7_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_15_005.read2.fastq;
cp Kafue2a_BC4-BC8_R1.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_005.read1.fastq; cp Kafue2a_BC4-BC8_R2.fastq ${SCRATCH}/RAD-faex/NGS-map/data/Chiou_14_005.read2.fastq;

exit